### PR TITLE
Feature/spline ranks rebased

### PR DESCRIPTION
**Pull request by juliolrmonteiro**
Changed utils::rank so that it allows both linear and spline curve (using mapped points) for ranks.
Includes reviewed tests for accounts, forum, harvest and organization contracts to match the new distribution.

## Edit

See constitution / game guide page 38 - "individual Accounts Total Contribution Scores"
Also page 50 same thing for orgs

There's been a change of spec, we need both linear and spline curves. 

The final contribution score for orgs and individuals should use the linear curve.

All other instances should use the spline curve.

## Spec
Add the linear rank back in, create 2 methods, rank_spline and rank_linear, change the code so the right one is used in the right places. 

## Deployment

- Accounts
- Harvest
- Forum
- Organization

### CODE REVIEW

**Comment by juliolrmonteiro** [comment]
This is the rebased version on top of the current master. Double checked and verified.
3 tests are not passing, please help!

```
scripts/seeds.js test accounts:
✖  Given seedsuseraaa punished: should have the correct status
    ---------------------------------------------------------------
error fired ReferenceError: resident is not defined
        operator: deepEqual
        diff: "resident" => "visitor"
        source: at checkUserStatus (/home/monteiro/src/seeds-contracts/test/accounts.test.js:1624:5)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /home/monteiro/src/seeds-contracts/test/accounts.test.js:1701:3

  passed: 79,  failed: 1  of 80 tests  (22.9s)
  
scripts/seeds.js test forum
   depreciate    ✖  Error: Not enough arguments to call onperiod action in forum.seeds contract
    -------------------------------------------------------------------------------
        operator: deepEqual
        diff: 
        source: at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

  passed: 9,  failed: 1  of 10 tests  (4.3s)

scripts/seeds.js test harvest:
  passed: 44,  failed: 0  of 44 tests  (3m 10.4s)

scripts/seeds.js test organization
    transfer to org
    TRANSACTION ERROR: Error: serialization time limit 15000us exceeded
    Error on actions: [{"account":"token.seeds","name":"transfer","authorization":[{"actor":"testorg5","permission":"active"}],"data":{"from":"testorg5","to":"join.seeds","quantity":"15.0000 SEEDS","memo":""}},{"account":"policy.seeds","name":"create","authorization":[{"actor":"policy.seeds","permission":"active"}],"data":{"account":"policy.seeds","backend_user_id":"mqofwc4k","device_id":"mqofwc4k","signature":"","policy":""}}]    ✖  Error: serialization time limit 15000us exceeded
    ----------------------------------------------------
        operator: deepEqual
        diff: 
        source: at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

  passed: 42,  failed: 1  of 43 tests  (1m 42.3s)

```
(Also eventually receiving other errors like '✖  Error: serialization time limit 15000us exceeded`

**Comment by n13** [comment]
Code looks great, running tests now

**Comment by n13** [comment]
accounts fails 3 tests   passed: 77,  failed: 3  of 80 tests  (20.8s)

**Comment by n13** [comment]
Fixed unit tests for accounts, harvest, forum, organization on master branch

**Review by n13 — CHANGES_REQUESTED** [review]
@juliolrmonteiro 

I merged master into this branch and made sure unit tests for accounts, harvest, forum, and organization worked

But accounts unit test still fails - let me know if you have any idea here - its only 1 failing test, I assume it has something to do with spline ranks

Can't accept PR with failing unit tests

MASTER:
  passed: 80,  failed: 0  of 80 tests  (20.8s)

This branch:
  passed: 79,  failed: 1  of 80 tests  (21.1s)

```
    ✔  Given seedsuseraaa punished: should have the correct removed flags points
    ✔  Given user punished: should have the correct reputation
    ✖  Given seedsuseraaa punished: should have the correct status
    ---------------------------------------------------------------
error fired ReferenceError: resident is not defined
        operator: deepEqual
        diff: "resident" => "visitor"
        source: at checkUserStatus (/Users/nik/work/seeds/seeds-contracts/test/accounts.test.js:1624:5)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async /Users/nik/work/seeds/seeds-contracts/test/accounts.test.js:1701:3
```

I don't know why this is happening otherwise I'd just fix it... can you take a look?

**Comment by juliolrmonteiro** [comment]
Had to change the rep threshold to pass the test (now using spline rank)
```
  passed: 80,  failed: 0  of 80 tests  (22.8s)
```

**Comment by n13** [comment]
## DEploy

Testing master branch unit tests first - make sure they work

./scripts/seeds.js run accounts forum harvest organization
./scripts/seeds.js test accounts
./scripts/seeds.js test forum
./scripts/seeds.js test harvest
./scripts/seeds.js test organization

In this one, the test for harvest failed, but it appears to be a bug in the test, not in the code. So I changed the test. Maybe you can look at it as well @juliolrmonteiro  but I will deploy this  now

**Review by n13 — APPROVED** [review]
I had to fix a unit test but otherwise looks good

**Pull request merged**
