### PR TITLE
Funding Fee and Referendum fee burning #61

### PR DESCRIPTION
**Pull request by IanMendozaJaimes**
- Added parameters: `propmaxstake` and `propstakeper`
- Added validations to: `vote_aux`, `onperiod` and `stake` 

## Deployment

- [ ] Deploy Settings
- [ ] Deploy Proposals when App is ready

### CODE REVIEW

**Comment by n13** [comment]
This is for #61

**Comment by n13** [comment]
I had to change is_enough_stake as it wasn't doing as intended

The idea was the fee is 5% of the proposal funding request, but at minimum 555, and at maximum 11,111 

So it defaults to 5%, but is capped.

I also made a change where proposals that do not have enough stake are not moved to "active" - this is less confusing for clients as nobody can vote on these anyway.

**Comment by n13** [comment]
Since staking is now rather complicated, I am considering adding a field so people know how much they have to stake

**Comment by n13** [comment]
Added minstake table for proposals. Otherwise clients will be overwhelmed trying to figure this out.

**Comment by n13** [comment]
@IanMendozaJaimes I made a few changes please check and comment here

**Comment by IanMendozaJaimes** [comment]
Hello @n13, I checked the changes and everything seems great. 

The only thing we notice is that in this line:
https://github.com/JoinSEEDS/seeds-smart-contracts/blob/feature/funding-fee-burning/src/seeds.proposals.cpp#L353
the validation for the proposal stake is not necessary anymore since it is being checked now within `onperiod` action

Is there anything else to be done for this issue?

**Comment by n13** [comment]
@IanMendozaJaimes I also added a minstake table as I feel it's going to be too error prone and complicated to know what the value is for apps. Just a service.

**Pull request merged**
