### PR TITLE
Accept Vouch and Un-vouch on penalty #233

### PR DESCRIPTION
**Pull request by IanMendozaJaimes**
- Added a new table for vouches
- Added tests
- Added a migration function

### CODE REVIEW

**Comment by n13** [comment]
## Deployment

- update Accounts contract
- run migration action

**Comment by n13** [comment]
@IanMendozaJaimes onboarding test fails

./scripts/seeds.js test onboarding

    ✖  Given invited new user: should have new vouch entry
    -------------------------------------------------------
        operator: deepEqual
        expected: [0, 1]
        diff: [
          1: 1 => 0
        ]
        source: at /Users/nik/work/seeds/seeds-contracts/test/onboarding.test.js:425:5
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Review by n13 — CHANGES_REQUESTED** [review]
Please fix onboarding test

Also: I fixed some ecc errors we got because of changing library, please check into it and perhaps remove the other / old "ecc" import, or the "getEcc()" function. 

I noticed that getECC is getting the sha256 function from a different version of the eosio.ecc package, which made it not work

That version returns an array of integers

The new version returns a hex string

The old version didn't work so my quick fix was to fix it in one place to make onboarding and accounts user tests work again (invite function)

Please check ;)

**Comment by IanMendozaJaimes** [comment]
Hello @n13, I added the requested changes:
- I fixed the sha256 function in the helper, now onboarding tests work
- I removed eosjs-ecc from package.json, the eosjs v21 library doesn't use it as eosjs-ecc is deprecated and unmaintained, that's why I preferred to keep using the ecc from the eosjs v21}
- Also, I added the attribute `points` to the `punish` function, it is not used in this issue but I added it because it is used in the flagging issue, so that should cause less problems when merging

**Comment by n13** [comment]
Works perfectly, thank you

**Review by n13 — APPROVED** [review]

**Pull request merged**
